### ISSUE TITLE
Resources page in User Guide

### ISSUE THREAD

**Issue by pdurbin** [opendp/opendp-documentation#28]
Today @raprasad brought up to me and @anniewu332  that it might be nice to list some resources on differential privacy (not specific to OpenDP). For now, Raman and I are thinking there could be a "Resources" page in the User Guide.

Please feel free to edit the following list:

- Differential privacy: A primer for a non-technical audience: https://salil.seas.harvard.edu/publications/differential-privacy-primer-non-technical-audience
- The Algorithmic Foundations of Differential Privacy (recommended by a potential contributor): https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf
- ...

**Comment by Shoeboxam** [comment]
The two above are what I would consider the canonical level 0 and level 1 introductions.
- On the complexity of DP: https://privacytools.seas.harvard.edu/files/privacytools/files/complexityprivacy_1.pdf
    * what I would consider a level 2 introduction to a bunch of concepts in the field
- Laplace mechanism: https://people.csail.mit.edu/asmith/PS/sensitivity-tcc-final.pdf
- Snapping mechanism and how floating-point numbers and the laplace mechanism leak: 
    https://www.microsoft.com/en-us/research/wp-content/uploads/2012/10/lsbs.pdf
- Exponential mechanism: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/mdviadp.pdf
- Geometric mechanism: https://arxiv.org/pdf/1709.05396.pdf (not the first geometric mech paper, but more approachable)
- More on sample/aggregate, and quantiles: https://cs-people.bu.edu/ads22//pubs/2011/stoc194-smith.pdf
- Gradient descent: https://arxiv.org/pdf/1607.00133.pdf
- Renyi DP: https://arxiv.org/pdf/1702.07476.pdf
- zCDP: https://arxiv.org/pdf/1605.02065.pdf

**Comment by raprasad** [comment]
- Nice intro level presentation: https://www2.census.gov/cac/nac/meetings/2019-05/garfinkel-privacy-confidentiality-protection.pdf
- More resources: https://simson.net/page/Differential_privacy
---
MS Broadband paper: https://arxiv.org/pdf/2103.14035.pdf

**Comment by Shoeboxam** [comment]
From Salil:
https://privacytools.seas.harvard.edu/courses-educational-materials

**Comment by anniewu332** [comment]
Can we already put the "Resources" page up on our doc site and/or our website?

**Comment by pdurbin** [comment]
The doc site is a bit in flux (we're working on moving the source to the main repo at https://github.com/opendp/opendp/pull/170 ) but I don't see why these resources couldn't go on the website, like you said.

While I'm commenting, Here are a few more resources from Salil and Mike from Slack:

- Two more resources: this chapter is more up-to-date and a bit more aimed at practitioners than the primer: https://admindatahandbook.mit.edu/book/latest/diffpriv.html
- And differentialprivacy.org has more resources too
- https://uvm-plaid.github.io/programming-dp/notebooks/cover.html

**Comment by pdurbin** [comment]
Closing in favor of https://github.com/opendp/opendp/issues/272

Some more responses via Slack:

We have a list of resources here (click on "Learning about DP -> Books and Surveys"): https://privacytools.seas.harvard.edu/courses-educational-materials

Two more resources: this chapter is more up-to-date and a bit more aimed at practitioners than the primer: https://admindatahandbook.mit.edu/book/latest/diffpriv.html

And https://differentialprivacy.org has more resources too
