### ISSUE TITLE
Convert this repo to SmartNoise docs only

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp-documentation#47]
- The main OpenDP library docs will live in opendp/opendp and be built via CI
- [x] "Downsize" these docs to only the SmartNoise section
- [x] Point to the docs.smartnoise.org url
- [ ] Add a link from docs.**opendp**.org to docs.**smartnoise**.org - see https://github.com/opendp/opendp/issues/240
- [x] Rename repository to ~~smartnoise-docs~~ docs.smartnoise.org

**Comment by pdurbin** [comment]
@raprasad please check out https://docs.smartnoise.org which should now look something like this:

<img width="1203" alt="Screen Shot 2021-08-13 at 3 34 43 PM" src="https://user-images.githubusercontent.com/21006/129409947-b2df10fa-ce8f-462f-9e34-fc0968d9301f.png">

The only remaining item from above is this one:

- Add a link from docs.opendp.org to docs.smartnoise.org

Of course, if there's more we should do for this initial reorg before closing this issue, that's fine.

Also, we briefly discussed moving issues to other repos but after reviewing them quickly, I think we should discuss this more. I didn't create most of them and I don't know how many are still relevant.

**Comment by pdurbin** [comment]
> Add a link from docs.opendp.org to docs.smartnoise.org

Ok, I created an issue to track this remaining item: https://github.com/opendp/opendp/issues/240

Closing.
