### ISSUE TITLE
sphinx shell for docs

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp-documentation#5]
- basic menus
- initial content
  - quickstart: https://github.com/opendp/smartnoise-core-python
  - api guide (link or embed). (#2)
  - notebooks embed + binder link. (#4) 
    - https://github.com/opendp/smartnoise-samples/blob/master/analysis/basic_data_analysis.ipynb

**Comment by pdurbin** [comment]
I stubbed out a quickstart in 134687b.

**Comment by pdurbin** [comment]
I just added a fair amount of content based on the outline in the "Proposed Information Architecture for OpenDP Documentation" doc we've been discussing: https://docs.google.com/document/d/1f4XWFxDL6Dwu68bjtpdO8AYfXaEL8URBDn4Lc943zTA/edit

I'll paste a screenshot below of how it looks.

I'm ready for more feedback. The site is now at https://docs.opendp.org

At some point we should probably close this broad "shell" issue and work on more specific issues.

<img width="1120" alt="Screen Shot 2021-05-14 at 4 38 17 PM" src="https://user-images.githubusercontent.com/21006/118326661-4265d080-b4d3-11eb-946d-db2a324cd033.png">
