### ISSUE TITLE
deploy docs via github actions

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp-documentation#8]
- initial script to deploy the shell site to the `gh-pages` branch
- opendp.org domain such as: `test-docs.opendp.org`

example at https://github.com/opendp/smartnoise-core/blob/develop/.github/workflows/rust.yml

**Comment by pdurbin** [comment]
Good progress in pull request #9 

Here's how it looks, deployed to http://test-docs.opendp.org

<img width="1137" alt="Screen Shot 2021-03-26 at 5 31 05 PM" src="https://user-images.githubusercontent.com/21006/112694685-25107080-8e59-11eb-9945-2294adefafb4.png">

**Comment by raprasad** [comment]
The Action is marked as "failed" if there is no new content to push to the doc site.
- Example, updating the repository's README will not result in updated sphinx pages and the action will fail/error when pushing go gh-pages
- Can an "if" statement be added?
  - If the gh-pages is up to date (`Your branch is up to date with 'origin/gh-pages'`):
    - the action continues/ends versus fails? `

**Comment by pdurbin** [comment]
I meant to put this in a single commit but I used `continue-on-error` in 91ab44d and 0e74a85 to prevent the "commit" step from stopping the final push to the gh-pages branch.
